### ISSUE TITLE
ValueError while drawing on frames in an animated GIF

### ISSUE THREAD

**Issue by obskyr** [python-pillow/Pillow#1592]
When trying to draw on frames in a certain animated GIF, I get the following traceback:

```
Traceback (most recent call last):
  File "C:\kana\strokeorder\deborder.py", line 28, in <module>
    deborder('chi.gif')
  File "C:\kana\strokeorder\deborder.py", line 19, in deborder
    draw.line((topLeft, topRight),       fill=(255, 255, 255))
  File "C:\Python27\lib\site-packages\PIL\ImageDraw.py", line 182, in line
    ink, fill = self._getink(fill)
  File "C:\Python27\lib\site-packages\PIL\ImageDraw.py", line 129, in _getink
    ink = self.palette.getcolor(ink)
  File "C:\Python27\lib\site-packages\PIL\ImagePalette.py", line 101, in getcolor
    self.palette = [int(x) for x in self.palette]
ValueError: invalid literal for int() with base 10: ''
```

It's incredibly odd that `''` should appear iterating through an instance of string / bytes. How would that even yield an empty string? Shouldn't it be guaranteed to always return a string of length 1...?

On Pillow 2.9.0, I tried going into the source of Pillow and changing `int(x)` to `ord(x)` in the source for... I don't know, good measure or something. Turns out that actually *did* fix it - kind of. The image was saved as grayscale, which it wasn't originally. Trying that on Pillow 3.0.0, however, yields the following traceback:

```
Traceback (most recent call last):
  File "C:\kana\strokeorder\deborder.py", line 28, in <module>
    deborder('chi.gif')
  File "C:\kana\strokeorder\deborder.py", line 26, in deborder
    frame.save('resave-' + filename, save_all=True, transparency=transparency)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 1665, in save
    save_handler(self, fp, filename)
  File "C:\Python27\lib\site-packages\PIL\GifImagePlugin.py", line 319, in _save_all
    _save(im, fp, filename, save_all=True)
  File "C:\Python27\lib\site-packages\PIL\GifImagePlugin.py", line 356, in _save
    first_frame = getheader(im_frame, palette, im.encoderinfo)[0]
  File "C:\Python27\lib\site-packages\PIL\GifImagePlugin.py", line 581, in getheader
    used_palette_colors = _get_used_palette_colors(im)
  File "C:\Python27\lib\site-packages\PIL\GifImagePlugin.py", line 537, in _get_used_palette_colors
    for count in im.histogram():
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 1225, in histogram
    self.load()
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 752, in load
    self.im.putpalette(*self.palette.getdata())
ValueError: unrecognized raw mode
```

Here's the fairly simple source code:

```python
from PIL import Image, ImageDraw

def deborder(filename):
    frame = Image.open(filename)
    frameNo = 0
    while True:
        try:
            frame.seek(frameNo)
        except EOFError:
            break
        draw = ImageDraw.Draw(frame)
        
        topLeft = (0, 0)
        topRight = (frame.size[0] - 1, 0)
        bottomLeft = (0, frame.size[1] - 1)
        bottomRight = (frame.size[0] - 1, frame.size[1] - 1)
        
        draw.line((topLeft, topRight),       fill=(255, 255, 255))
        draw.line((topLeft, bottomLeft),     fill=(255, 255, 255))
        draw.line((bottomLeft, bottomRight), fill=(255, 255, 255))
        draw.line((topRight, bottomRight),   fill=(255, 255, 255))
        
        frameNo += 1
    
    frame.save('resave-'+filename, save_all=True)

deborder('chi.gif')
```

And here's the image file in question. Just put it in the same folder as the source, and name it "chi.gif" to try for yourself. GitHub doesn't change the file around at all - I checked, the checksum matches the original file's.

![chi](https://cloud.githubusercontent.com/assets/4363779/11770490/879b4a32-a1ff-11e5-8bab-c766e09c6ba4.gif)

I do think there most likely is something wrong with the image file, but since web browsers and image viewers handle it without complaint, I feel Pillow should too. What's up?

**Comment by radarhere** [comment]
Hi. Thanks for reporting.

From my investigation so far, I can see that the error you're reporting occurs in Python 2.

In Python 3, I get the `ValueError: unrecognized raw mode` exception. The raw mode in question is RGBA;L. As pointed out in Issue #1280, this is not a part of this list - https://github.com/python-pillow/Pillow/blob/master/libImaging/Unpack.c#L1080 - and so that is the explanation for the Python 3 problem.

**Comment by radarhere** [comment]
Is the image one that could be included in our tests and distributed under the Pillow license? That would allow a fix and test to be written for the `invalid literal` error.

**Comment by obskyr** [comment]
It is, in fact! It's licensed under CC0 - that is, public domain. [The original source(https://commons.wikimedia.org/wiki/File:Hiragana_%E3%81%A1_stroke_order_animation.gif) is user Sirgazil on Wikipedia.

**Comment by radarhere** [comment]
Thanks. I've now created a PR to fix the `invalid literal` issue.

**Comment by The-Penultimate-Defenestrator** [comment]
@radarhere Did this ever get resolved? I'm seeing this error.

In my situation, I'm trying to use `ImageDraw` with images from Google Images. About one in 10 images produces this error when I try to use `ImageDraw.Draw().text`. My traceback is:

```
File "memefarm/pilutil.py", line 37, in labelImage
    d.text(coords, text, fill=color)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PIL/ImageDraw.py", line 253, in text
    ink, fill = self._getink(fill)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PIL/ImageDraw.py", line 129, in _getink
    ink = self.palette.getcolor(ink)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PIL/ImagePalette.py", line 101, in getco
lor
    self.palette = [int(x) for x in self.palette]
ValueError: invalid literal for int() with base 10: ''
```

**Comment by radarhere** [comment]
Hi. No, this is has not been resolved. I suggested a fix, which has some discussion over at #1593. If you have anything to contribute to help it move along, please feel free to do so.

**Comment by zinefer** [comment]
How did you solve the `ValueError: unrecognized raw mode` error? I understand that the pallete mode is invalid somehow but I can't figure out how to fix it. Here is my code:

```
img = Image.open('src.gif')

print(img.mode)                 # P
print(len(img.palette.palette)) # RGB
print(img.palette.rawmode)      # 768

img.save('tmp.gif', save_all=True)
```

**Comment by zinefer** [comment]
I never did manage to get this solved with just PIL. The closest I got was pulling an old version of [gifmaker.py](https://github.com/python-pillow/Pillow/blob/8dc8a1235e1c02a4946cfc28d2754965c941c482/Scripts/gifmaker.py) and trying to use it on an array of pil images. It worked as long as I didn't draw on the images. I even tried saving the frames out to the hard drive and then reopening them and trying to use gifmaker.py to make a gif that way. No luck.

I did end up finding a way to do this in python:
```
img = Image.open('src.gif')
sequence = []
frameNo = 0
while True:
  try:
    img.seek(frameNo)
  except EOFError:
    break
          
  newimg = Image.new("RGB", img.size)
  newimg.paste(img)

  draw = ImageDraw.Draw(newimg);
    
  #draw here

  open_cv_image = numpy.array(newimg)
  sequence.append(open_cv_image)
    
  frameNo += 1

imageio.mimsave('temp.gif', sequence);
```

You can find imageio [here](http://imageio.github.io/). Hopefully we can get these GIF issues solved but in the mean time hopefully I can save someone else some headache.

**Comment by obskyr** [comment]
I ended up using ImageMagick for my case - turns out it's very versatile with its command line options. To remove the border from my GIFs, I wrote the following batch script which works just fine.

```bat
@ECHO OFF

for /f %%f  in ('dir /b *.gif') do (
	echo Debordering %%f...
	convert %%f -crop 318x238+1+1 -background white -fill white -opaque #FEFFFC %%f
)
echo All done!
```

Still doesn't help Pillow, though. It looks like the fix, #1593, got stuck a bit in the politics pipeline, but is slated for 3.3.0, releasing July 1st according to #1800. Hope nothing gets in the way this time.

**Comment by radarhere** [comment]
Just for the record, noting that this has been resolved by #1985.

**Comment by radarhere** [comment]
@zinefer The `ValueError: unrecognized raw mode` error has not been solved. You're welcome to request that this issue be re-opened, or to start another one. From my investigation, the problem is that the conversion is not part of this list - https://github.com/python-pillow/Pillow/blob/faeb269e303fbbc9385ec123b3333ba0c02d93e3/libImaging/Unpack.c#L1142

**Comment by obskyr** [comment]
@radarhere As I mentioned in [a comment on the other issue](https://github.com/python-pillow/Pillow/pull/1593#issuecomment-226610676), however, RGBA;L ([which you mentioned was the raw mode in question](https://github.com/python-pillow/Pillow/issues/1592#issuecomment-164316431)) [is part of the list](https://github.com/python-pillow/Pillow/blob/faeb269e303fbbc9385ec123b3333ba0c02d93e3/libImaging/Unpack.c#L1210). So what's up with that?

**Comment by radarhere** [comment]
The problematic conversion for this issue is from RGB to RGBA;L. The only instance of RGBA;L in the list is from RGBA to RGBA;L.

**Comment by serg472** [comment]
Google brought me here. I had the same palette exception `invalid literal for int() with base 10: ''` when drawing on a transparent PNG. The solution was to convert the image to RGBA (or RGB if you don't want to keep the transparency) before drawing, maybe it helps someone:

	img = Image.open(filepath).convert('RGBA')
	dr = ImageDraw.Draw(img)
	dr.rectangle([0,0,100,100, outline='#ff0000')
	img = img.convert('P', palette=Image.ADAPTIVE)
	img.save(iconpath, 'PNG', optimize=True)
