### ISSUE TITLE
ValueError: tile cannot extend outside image on fromarray()

### ISSUE THREAD

**Issue by NicoLivesey** [python-pillow/Pillow#3902]
### What did you do?
Trying to convert an array into Image after crop

### What did you expect to happen?
Works

### What actually happened?
`ValueError: tile cannot extend outside image`

### What are your OS, Python and Pillow versions?

* OS: Ubuntu 18
* Python: 3.6...
* Pillow: 5.1.0

I basically run a script over more than 50k images and this part fails randomly. I have seen related issues such as #3044 and other ones on Stackoverflow but this never happens on an already cropped image.

Thank you in advance !

```python
crop = image[a:b, c:d]
crop_pil = Image.fromarray(crop)
```

**Comment by hugovk** [comment]
Please can include the image that causes the problem?

Please can also include a self-contained, copy-pastable code sample? Be concise with code posted. Guidelines on how to provide a good bug report:

* https://stackoverflow.com/help/mcve

Bug reports which follow these guidelines are easier to diagnose, and are often handled much more quickly. Thank you!

**Comment by NicoLivesey** [comment]
I am really sorry but I cannot provide neither the image nor the full code and the code sample is the only interesting part of the process. Before that I get coordinates from an object detection model. 
In the code example, the crop that causes the problem is:

```
crop = image[484:852, 22:598]
crop_pil = Image.fromarray(crop)
```

Once again, I am really sorry that I cannot fit your bug report policy but I just wanted to know if anyone already met an issue like this. I am really thankful for your help.

**Comment by radarhere** [comment]
I imagine you'll say that it is not the same, but there is https://github.com/python-pillow/Pillow/issues/2383#issuecomment-278113341, which is fixed in the unreleased master branch.

Depending on your architecture, there is #3841.

Could you try using the master branch version of Pillow, rather than Pillow 5.1.0?

**Comment by radarhere** [comment]
In case it helps, Pillow 6.1.0 has now been released, which fixes both the issues that I mentioned.

**Comment by NicoLivesey** [comment]
Thank you very much !

**Comment by mk-45** [comment]
ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple ple  help ME ME!

**Comment by vnyk** [comment]
I have pillow 6.10 installed and still getting this error.
Did anyone found any alternative solution

**Comment by radarhere** [comment]
@vnyk could you create a new issue describing your problem, with a self-contained example including a source image?

**Comment by vnyk** [comment]
@radarhere I did it here #4517
