### ISSUE TITLE
Unexpected memory consumption since release 8.3.0

### ISSUE THREAD

**Issue by helgeerbe** [python-pillow/Pillow#5797]
### What did you do?
I'm the owner of [picframe](https://github.com/helgeerbe/picframe).  This is a picture frame viewer for raspi, controlled via mqtt and automatticly integrated as mqtt device in homeassistant.

In an endless loop this programs displays one image on the frame, opens the next one and blend the new image smoothly in. To extract the image data PIL is used. So at the end just 2 images are kept in memory.

### What did you expect to happen?
A stable memory consumption over a period of time. This was true up and including release 8.2.0. 
I'm logging in a influxdb the system load and found this behavior.
![Bildschirmfoto 2021-10-27 um 10 30 26](https://user-images.githubusercontent.com/59169507/139078272-3da8b3ae-ef9e-4744-96c7-51aeb11057e4.png)

Memory consumption is as expected stable. When suddenly the sawtooth line appears. (High cpu load two most left yellow peaks are the nightly backups).

What have I done?
- apt get full-upgrade
- pull all python modules required by picframe to their latest releases

````sh
pi@picframe:~ $ python3 --version
Python 3.7.3
pi@picframe:~ $ picframe -v
INFO:start.py:starting ['/home/pi/.local/bin/picframe', '-v']
picframe version:  0+untagged.365.gfc64728

Checking required packages......
PIL :  8.4.0
exifread :  2.3.2
pi3d :  2.48
yaml :  6.0
paho.mqtt :  1.5.1
iptcinfo3 :  2.1.4
numpy :  1.21.2
ninepatch : installed, but no version info

Checking optional packages......
pyheif :  0.5.1
````

### What actually happened?

Starting with release 8.3.0 memory consumption is strange. Picframe starts with 6% total memory. While running, PIL allocated permanently memory which is freed frequently (sawtooth line). But at the end memory consumption  reaches 100% in total and picframe crashes.

### What are your OS, Python and Pillow versions?

* OS: Rasbian
  Description:	Raspbian GNU/Linux 10 (buster)
  Release:	10
  Codename:	buster
  Linux picframe 5.10.63-v7+ 1459 SMP Wed Oct 6 16:41:10 BST 2021 armv7l GNU/Linux
* Python: 3.7.2
* Pillow: 8.3.0 - 8.4.0 (earlier releases behave as expected)

### issue in picframe

Issue for picframe is tracked [here](https://github.com/helgeerbe/picframe/issues/182)

**Comment by radarhere** [comment]
Given what you're seeing, I suspect this is due to #5379, where we replaced our Image's `__array_interface__` with `__array__`.

Are you sure this isn't a problem better addressed by the numpy team?

**Comment by rlevine** [comment]
Hit the same issue - poor 512MB Heroku dynos didn't know what hit them. "Memory quota vastly exceeded." \*chuckle\*
36 2967x2992 png images with alpha channel, 33.86MB each, High water mark at 1.55GB, 1.2GB of memory that didn't go away.

```Line #    Mem usage    Increment   Line Contents
============================================================
   973    181.9 MiB    181.9 MiB   @profile
   974                             def color_substitute(image, old_color, new_color):
   975    260.9 MiB     79.0 MiB       data = numpy.array(
   976    181.9 MiB      0.0 MiB       image)  # "data" is a height x width x 4 (assuming an alpha channel) numpy array
   977    260.9 MiB      0.0 MiB       red, green, blue, alpha = data.T  # Transpose bands
   978                                         
   979                                 # Replace old color with new color... (leaves alpha values alone...)
   980    278.8 MiB     17.9 MiB       color_areas = (red == old_color[0]) & (green == old_color[1]) & (blue == old_color[2])
   981    278.8 MiB      0.0 MiB       color_areas = color_areas.T  # transpose the array; back in the same orientation as original
   982    279.0 MiB      0.2 MiB       data[..., :-1][color_areas] = new_color  # vegematic
   983                                         
   984    279.0 MiB      0.0 MiB       return Image.fromarray(data)
```

Python 3.10.0
PIL :  8.4.0
numpy :  1.21.4

**Comment by radarhere** [comment]
Hi @rlevine. To confirm my theory, would you be able to install https://github.com/radarhere/Pillow/tree/numpy (or just open PIL/Image.py and make the https://github.com/radarhere/Pillow/commit/27793058ab9681b5761ffa43554b155057e0f96c changes) and see if that fixes the problem?

**Comment by rlevine** [comment]
Chicken dinner. Memory for 36 passes through the function goes from 1488 MiB to 267 MiB, about 1.28GB difference. 
Somebody missing a decref for the underlying cstruct?

Thanks!

Rick

***

   Pillow==8.4.0 as distributed

   ```984   1488.4 MiB      0.0 MiB           1       return Image.fromarray(data)```

   8.4.0 with radarhere@2779305 applied

   ```984    268.6 MiB      0.0 MiB           1       return Image.fromarray(data)```

**Comment by homm** [comment]
I'm investigating this. The fix really simple:

```python
        class ArrayData:
            def __init__(self, new):
                __array_interface__ = new
```

But I still don't understand the nature of cyclic references here. That's what I see:

```python
import numpy, gc
from PIL import Image
im = Image.new('RGB', (4, 4))

try:
   gc.disable()
   gc.collect()
   gc.set_debug(gc.DEBUG_LEAK | gc.DEBUG_STATS)
   numpy.array(im)
   gc.collect()
   for item in gc.garbage:
      print('>>>', type(item), repr(item))
finally:
   gc.set_debug(0)
   gc.enable()
   gc.garbage.clear()
   gc.collect()
```

```
>>> <class 'tuple'> (4, 4, 3)
>>> <class 'dict'> {'shape': (4, 4, 3), 'typestr': '|u1', 'version': 3, 'data': b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'}
>>> <class 'tuple'> (<class 'object'>,)
>>> <class 'dict'> {'__module__': 'PIL.Image', '__array_interface__': {'shape': (4, 4, 3), 'typestr': '|u1', 'version': 3, 'data': b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'}, '__dict__': <attribute '__dict__' of 'ArrayData' objects>, '__weakref__': <attribute '__weakref__' of 'ArrayData' objects>, '__doc__': None}
>>> <class 'type'> <class 'PIL.Image.Image.__array__.<locals>.ArrayData'>
>>> <class 'getset_descriptor'> <attribute '__dict__' of 'ArrayData' objects>
>>> <class 'getset_descriptor'> <attribute '__weakref__' of 'ArrayData' objects>
>>> <class 'tuple'> (<class 'PIL.Image.Image.__array__.<locals>.ArrayData'>, <class 'object'>)
```

And from my point of view there couldn't be any circular refs.

**Comment by homm** [comment]
Oh, I get it finally. It realises that every class definition is a circular reference to itself:

```python
In [15]: class ArrayData: 
    ...:     pass 
    ...: ArrayData.__mro__                                                                                                      
Out[15]: (__main__.ArrayData, object)
```

The smallest case which will grow infinitely:

```python
gc.disable()
while True:
    class ArrayData:
        pass
 ```

So we just should move `ArrayData` definition to `Image.` namespace, for example:

```python
class Image:
    class _ArrayData:
        def __init__(self, new):
            __array_interface__ = new
                
    def __array__(self, dtype=None):
        ...
        return np.array(self._ArrayData(new), dtype)
```

**Comment by homm** [comment]
By the way, if anyone curios about performance of Pillow → numpy conversions, there is an article with a helper function which will be significantly faster: https://uploadcare.com/blog/fast-import-of-pillow-images-to-numpy-opencv-arrays/

Unfortunately, this enhancement is barely implementable within Pillow codebase.

**Comment by homm** [comment]
@rlevine 
> Somebody missing a decref for the underlying cstruct?

Nope, this is totally garbage pressure. We should always be very careful with circular references when working with large objects.

**Comment by radarhere** [comment]
Thanks @homm. I've created PR #5844 with your suggestion.

**Comment by rlevine** [comment]
> Thanks @homm. I've created PR #5844 with your suggestion.

Works! Thanks!

**Comment by pcicales** [comment]
I appear to be having this same issue with PIL==9.1.0.

I am observing the same sawtooth memory pattern, followed by 100% memory usage, when loading and unloading PIL images in a loop. The images are loaded using PIL, then converted to np arrays, then unloaded from memory using `.close()` and `= None`

**Comment by radarhere** [comment]
The original fix to this issue involved making `Image.__array__` more efficient. With the upcoming release of NumPy 1.23, we have the opportunity to simplify further by switching back to `Image.__array_interface__`.

Would you mind testing https://github.com/radarhere/Pillow/tree/numpy and seeing if that solves your problem?

**Comment by pcicales** [comment]
@radarhere Just installed. Here is the package info. I will be testing this shortly.

Previous:
`# Name                    Version                   Build  Channel
pillow                         9.1.0                     pypi_0    pypi

# Name                    Version                   Build                    Channel
numpy                       1.21.2                py37h20f2e39_0
numpy-base              1.21.2                py37h79a1101_0
`

Current:
`# Name                    Version                   Build  Channel
pillow                         9.2.0.dev0               pypi_0    pypi

# Name                    Version                   Build                    Channel
numpy                       1.21.2                py37h20f2e39_0
numpy-base              1.21.2                py37h79a1101_0
`

**Comment by pcicales** [comment]
@radarhere Seems to still have the leak - cpu mem gradually increases to 100%.

Should I revert back to an older version of PIL?

**Comment by radarhere** [comment]
8.2.0 is the version before changed from `__array_interface__` to `__array__`. That version would made sense, except that if that version would work, I would also have expect https://github.com/radarhere/Pillow/tree/numpy to work.

If there is any older version of Pillow that works for you, that would be useful debugging information to have.

Would you be able to open a new issue, specify your operating system details, and simple code to demonstrate the problem?

**Comment by helgeerbe** [comment]
Just to let you know. I upgraded to `9.1.0`and it worked for me. So it must be something else. It seems not to be my original reported issue.

**Comment by pcicales** [comment]
@radarhere Interesting - I will do so. I am trying to pinpoint where memory is not being released; do you have any recommendations on best practices for doing so? Currently I am just logging cpu memory, but I think it would be helpful for us if I could pinpoint the PIL/np operation that is causing the issue.

**Comment by wiredfool** [comment]
Try running it under valgrind, using the massif tool. It's slow, but it gives a really good profile of where and when memory is allocated.

**Comment by Rahul-Matta** [comment]
@wiredfool @pcicales @helgeerbe 
is it good to > Pillow:9.1.0 to avoid memory consumption?
I am using Pillow:8.4.0 currently it's causing all four processors would hit 100% usage on the libc library.

**Comment by wiredfool** [comment]
@Rahul-Matta That doesn't sound anything like what's happening here. You're best off posting a complete bug report as a new issue.

**Comment by Rahul-Matta** [comment]
Okay, @wiredfool https://github.com/python-pillow/Pillow/issues/6781 as new bug.
