### ISSUE TITLE
pip doesn't install the highest version

### ISSUE THREAD

**Issue by Zengyf-CVer** [python-pillow/Pillow#7294]
In python3.8, I used pip to install pillow, and found that it can only be installed to 9.5.0. I want to install version 10.0.0. Do I need any requirements?

**Comment by radarhere** [comment]
What is the pip command that you are running?

What operating system are you using? Are you on a 32-bit or 64-bit machine?

**Comment by Zengyf-CVer** [comment]
@radarhere 
windows 64-bit
pip install pillow --upgrade

**Comment by radarhere** [comment]
I think it should be working then. Can you post the full output when you run the command?

**Comment by Zengyf-CVer** [comment]
![image](https://github.com/python-pillow/Pillow/assets/41098760/81cabf80-96f8-4325-8220-6286e04f03c7)

**Comment by radarhere** [comment]
Could you try running `pip install --upgrade pip` and then running `pip install pillow --upgrade` again?

**Comment by Zengyf-CVer** [comment]
@radarhere 
pip has been upgraded to the latest, but the problem with pillow is still not resolved.

![image](https://github.com/python-pillow/Pillow/assets/41098760/3c9a7b4f-4848-4e1c-b7dc-767a81a4b4b2)

**Comment by radarhere** [comment]
Hmm.

If you would like an immediate solution, you could try downloading the Pillow 10 wheel directly - [Pillow-10.0.0-cp38-cp38-win_amd64.whl](https://files.pythonhosted.org/packages/5e/ae/0d98e3707678c96d86aec0fe5002637801892f17281cc123521ab929e8fd/Pillow-10.0.0-cp38-cp38-win_amd64.whl) - and then, from the directory where it is saved, run `pip install ./Pillow-10.0.0-cp38-cp38-win_amd64.whl`

That might work, or it might print an error message that will explain what is going on here.

**Comment by Zengyf-CVer** [comment]
@radarhere Thanks a lot, I still want to install directly via pip. Waiting for your fix.

**Comment by hugovk** [comment]
Can you try with different levels od verbose output? 

```sh
pip install --upgrade pip -v > v1.txt
pip install --upgrade pip -vv > v2.txt
pip install --upgrade pip -vvv > v3.txt
```

And then share the text files?

**Comment by homm** [comment]
> Looking in indexes: http://pypi.douban.com/simple

You have custom package index

**Comment by radarhere** [comment]
Thanks @homm 

Yes, http://pypi.douban.com/simple/pillow doesn't list Pillow 10, while https://pypi.org/simple/pillow/ does.
